# Generated by Django 2.2.5 on 2020-10-17 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20200730_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(blank=True, default='無', max_length=600, null=True, verbose_name='Ids')),
                ('ids_block', models.TextField(blank=True, default='無', max_length=600, null=True, verbose_name='Ids 坏死的')),
                ('done_status', models.BooleanField(default=True, verbose_name='是否做了')),
                ('block_status', models.BooleanField(default=True, verbose_name='是否有坏的任务')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '奔跑的任务',
                'verbose_name_plural': '奔跑的任务',
            },
        ),
    ]
