# Generated by Django 2.2.5 on 2020-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_running_way'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='running',
            options={'verbose_name': '千人任务', 'verbose_name_plural': '千人任务'},
        ),
        migrations.AddField(
            model_name='running',
            name='lock',
            field=models.BooleanField(default=False, verbose_name='锁死？'),
        ),
        migrations.AlterField(
            model_name='running',
            name='ids_block',
            field=models.TextField(blank=True, default='', max_length=600, null=True, verbose_name='Ids 坏死的'),
        ),
    ]
