# Generated by Django 2.2.5 on 2020-07-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20200705_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmsg',
            name='typed',
            field=models.SmallIntegerField(choices=[(1, '余额提醒'), (2, '客人再次光临的提醒'), (3, '系统事务预告'), (4, '杂项与其他提醒'), (111, '系统 APScheduler 进程已停止！！！'), (112, '客人意见反馈！！！'), (113, '平台数据备份状态反馈。')], default=1, null=True, verbose_name='消息类型'),
        ),
    ]
