# Generated by Django 2.2.5 on 2020-07-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_auto_20200705_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everytask',
            name='send_finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='預計發送時間'),
        ),
    ]
