# Generated by Django 2.2.5 on 2020-06-11 06:32

import Appis.Web.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=Appis.Web.models._img, verbose_name='图片')),
                ('img_tiny', models.ImageField(null=True, upload_to=Appis.Web.models._img_tiny, verbose_name='缩略图片')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='SMSConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='twilio', max_length=30, verbose_name='厂家标示')),
                ('sid', models.CharField(default='未知', max_length=200, verbose_name='账户 sid')),
                ('token', models.CharField(default='未知', max_length=200, verbose_name='账户 认证token')),
                ('sender', models.CharField(default='未知', max_length=120, verbose_name='发送者号码')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': 'SMS配置',
                'verbose_name_plural': 'SMS配置',
            },
        ),
        migrations.CreateModel(
            name='SystemMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, null=True, verbose_name='邮件Subject')),
                ('message', models.TextField(blank=True, default='無', max_length=600, null=True, verbose_name='邮件内容')),
                ('typed', models.SmallIntegerField(choices=[(1, '余额提醒'), (2, '客人再次光临的提醒'), (3, '系统事务预告'), (4, '杂项与其他提醒')], default=1, null=True, verbose_name='消息类型')),
                ('way', models.SmallIntegerField(choices=[(1, '短信'), (2, '电邮'), (3, 'Whats App')], default=1, null=True, verbose_name='发送消息的方式')),
                ('success_status', models.BooleanField(default=True, verbose_name='是否发送成功')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
            },
        ),
    ]
