# Generated by Django 2.2.5 on 2020-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_remove_img_named'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='h',
            field=models.CharField(max_length=60, null=True, verbose_name='高'),
        ),
        migrations.AddField(
            model_name='img',
            name='w',
            field=models.CharField(max_length=60, null=True, verbose_name='宽'),
        ),
    ]
