# Generated by Django 2.2.5 on 2020-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20200612_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='out_link',
            field=models.TextField(max_length=240, null=True, verbose_name='访问链接'),
        ),
    ]
