# Generated by Django 2.2.5 on 2020-07-30 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='标签名称')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='User.Tag', verbose_name='标签'),
        ),
    ]
