# Generated by Django 2.2.5 on 2020-08-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200730_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_named',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_named',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='名字'),
        ),
    ]
