# Generated by Django 2.2.5 on 2020-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200804_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_named',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_named',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='名字'),
        ),
    ]
