# Generated by Django 2.2.5 on 2020-06-11 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(default='0', max_length=90, verbose_name='极光短信任务ID 字段')),
                ('send_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='实际發送時間')),
                ('send_origin_time', models.DateTimeField(blank=True, null=True, verbose_name='预定發送時間')),
                ('temp_para', models.TextField(blank=True, default='無', max_length=600, null=True, verbose_name='模版参数')),
                ('time_rule_belong', models.SmallIntegerField(choices=[(0, '即時發送'), (1, '壹月後'), (2, '二月後'), (3, '三月後'), (4, '四月後'), (5, '五月後'), (6, '六月後'), (7, '七月後'), (8, '八月後'), (9, '九月後'), (10, '十月後'), (11, '十壹月後')], default=0, verbose_name='所属时间规则')),
                ('numed', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='所属索引值')),
                ('apply_status', models.NullBooleanField(default=None, verbose_name='对接是否成功')),
                ('send_status', models.BooleanField(default=False, verbose_name='短信是否已发送')),
                ('contact_id', models.IntegerField(default=0, verbose_name='联系人id')),
                ('jsms_response', models.TextField(blank=True, max_length=1000, null=True, verbose_name='极光 Response 返回解析结果储存')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '极光任務队列',
                'verbose_name_plural': '极光任務队列',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='SmsTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='任務名稱')),
                ('phoned', models.TextField(max_length=2000, null=True, verbose_name='手机号')),
                ('sms_template', models.CharField(max_length=240, verbose_name='短信內容')),
                ('send_time', models.DateTimeField(verbose_name='發送時間')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('every_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Record.EveryTask', verbose_name='极光任务队列表')),
            ],
            options={
                'verbose_name': '短信发送完成记录',
                'verbose_name_plural': '短信发送完成记录',
            },
        ),
        migrations.CreateModel(
            name='SmsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoned', models.CharField(max_length=60, null=True, verbose_name='手机号')),
                ('named', models.CharField(max_length=120, null=True, verbose_name='顾客名字')),
                ('task_status', models.NullBooleanField(default=False, verbose_name='任务申请状态')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='任务结束时间')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sms.Area', verbose_name='手机号码前缀')),
                ('sms_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sms.SmsTemplate', verbose_name='短信模版')),
            ],
            options={
                'verbose_name': '任務申请',
                'verbose_name_plural': '任務申请',
            },
        ),
        migrations.AddField(
            model_name='everytask',
            name='sms_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Record.SmsTask', verbose_name='所属任务申请表'),
        ),
    ]
