# Generated by Django 2.2.5 on 2020-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everytask',
            name='apply_status',
            field=models.NullBooleanField(default=None, verbose_name='应用标识'),
        ),
    ]
