# Generated by Django 2.2.5 on 2020-10-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0007_auto_20201017_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollect',
            name='plate_stats',
            field=models.SmallIntegerField(default=0, verbose_name='平台状态'),
        ),
    ]
