# Generated by Django 2.2.5 on 2020-06-26 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateField(default=django.utils.timezone.now, verbose_name='光顾時間')),
                ('now_index', models.IntegerField(default=0, verbose_name='当前已工作了几期')),
                ('apply_status', models.BooleanField(default=False, verbose_name='生效状态')),
                ('send_status', models.BooleanField(default=True, verbose_name='是否允许发送')),
                ('over_status', models.BooleanField(default=False, verbose_name='是否完结')),
                ('next_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次发邮件的時間')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '邮件任务申请列表',
                'verbose_name_plural': '邮件任务申请列表',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, null=True, verbose_name='邮件Subject')),
                ('message', models.TextField(blank=True, default='無', max_length=7200, null=True, verbose_name='邮件内容')),
                ('time_rule', models.SmallIntegerField(choices=[[0, '一次性'], [1, '每月'], [2, '每兩月'], [3, '每三月'], [4, '每四月'], [5, '每五月'], [6, '每六月'], [7, '每七月'], [8, '每八月'], [9, '每九月'], [10, '每十月'], [11, '每十一月'], [12, '每一年'], [13, '每兩年']], default=0, verbose_name='所属时间规则')),
                ('service', models.CharField(max_length=120, null=True, verbose_name='服务名称')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sms.Category', verbose_name='服务分类')),
            ],
            options={
                'verbose_name': '邮件模版',
                'verbose_name_plural': '邮件模版',
            },
        ),
        migrations.CreateModel(
            name='EmailCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_status', models.BooleanField(default=False, verbose_name='是否发送成功')),
                ('json_response', models.TextField(blank=True, default='無', max_length=400, null=True, verbose_name='回应的Response')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送時間')),
                ('index', models.IntegerField(default=1, verbose_name='第几期')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('email_apply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Additional.EmailApply', verbose_name='服务申请表')),
                ('email_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Additional.EmailTemplate', verbose_name='任务模版')),
            ],
            options={
                'verbose_name': '单期邮件记录',
                'verbose_name_plural': '单期邮件记录',
            },
        ),
    ]
