# Generated by Django 2.2.5 on 2020-06-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0002_auto_20200611_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailapply',
            name='last_time',
        ),
    ]
