# Generated by Django 2.2.5 on 2020-10-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='way',
            field=models.SmallIntegerField(choices=[(1, '短信'), (2, '电邮'), (3, 'Whats App')], default=1, null=True, verbose_name='发送消息的方式'),
        ),
    ]
