# Generated by Django 2.2.5 on 2020-06-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Additional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailapply',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Contact', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='emailapply',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Additional.EmailTemplate', verbose_name='所属模版'),
        ),
    ]
