# Generated by Django 2.2.5 on 2020-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0004_auto_20200829_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailapply',
            name='first_status',
            field=models.BooleanField(default=True, verbose_name='启用首封？'),
        ),
    ]
