# Generated by Django 2.2.5 on 2020-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0005_emailapply_first_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailapply',
            name='across_index',
            field=models.IntegerField(default=0, verbose_name='经过后台几期'),
        ),
    ]
