# Generated by Django 2.2.5 on 2020-10-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0006_emailapply_across_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailapply',
            name='nper',
            field=models.IntegerField(choices=[(0, '無限制數量'), (1, '只寄出一次'), (2, '寄出兩次'), (3, '寄出三次'), (4, '寄出四次'), (5, '寄出五次'), (6, '寄出六次'), (12, '寄出十二次')], default=0, verbose_name='期数'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='time_rule',
            field=models.SmallIntegerField(choices=[[0, '僅寄出一次'], [1, '每一個月(可重複寄出)'], [2, '每兩個月(可重複寄出)'], [3, '每三個月(可重複寄出)'], [4, '每四個月(可重複寄出)'], [5, '每五個月(可重複寄出)'], [6, '每六個月(可重複寄出)'], [7, '每七個月(可重複寄出)'], [8, '每八個月(可重複寄出)'], [9, '每九個月(可重複寄出)'], [10, '每十個月(可重複寄出)'], [11, '每十一個月(可重複寄出)'], [12, '每一年(可重複寄出)'], [13, '每兩年(可重複寄出)']], default=0, verbose_name='所属时间规则'),
        ),
    ]
