# Generated by Django 2.2.5 on 2020-08-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_auto_20200730_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everytask',
            name='jsms_response',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='短信平台 Response 返回解析结果储存'),
        ),
        migrations.AlterField(
            model_name='everytask',
            name='schedule_id',
            field=models.CharField(default='0', max_length=90, verbose_name='短信任务ID 字段'),
        ),
        migrations.AlterField(
            model_name='smstaskrecord',
            name='every_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Record.EveryTask', verbose_name='短信任务队列表'),
        ),
    ]
