# Generated by Django 2.2.5 on 2020-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Additional', '0002_auto_20200630_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailapply',
            name='nper',
            field=models.IntegerField(choices=[(0, '無限制期數'), (1, '仅一期'), (2, '二期'), (3, '三期'), (4, '四期'), (5, '五期'), (6, '六期'), (12, '十二期')], default=0, verbose_name='期数'),
        ),
    ]
