# Generated by Django 2.2.5 on 2020-06-30 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoned_prefix', models.CharField(max_length=30, null=True, verbose_name='手机号码前缀')),
                ('named', models.CharField(blank=True, max_length=60, null=True, verbose_name='地域名称')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '地域与电话号码前缀',
                'verbose_name_plural': '地域与电话号码前缀',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(default='未知', max_length=30, null=True, verbose_name='分类展示名字')),
                ('flag', models.SmallIntegerField(choices=[(1, '疫苗'), (2, '手術'), (3, '美容'), (21, '產品'), (22, '服務'), (23, '檢查')], default=1, null=True, verbose_name='分类')),
                ('way', models.SmallIntegerField(choices=[(1, '短信'), (2, '电邮'), (3, 'Whats App')], default=1, null=True, verbose_name='定位')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '服务分类',
                'verbose_name_plural': '服务分类',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(default='未知', max_length=60, verbose_name='服务名')),
                ('time_rule', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '即時發送'), (1, '壹月後'), (2, '二月後'), (3, '三月後'), (4, '四月後'), (5, '五月後'), (6, '六月後'), (7, '七月後'), (8, '八月後'), (9, '九月後'), (10, '十月後'), (11, '十壹月後')], max_length=25, null=True, verbose_name='时间规律')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(max_length=90, verbose_name='模版id')),
                ('sms_id_sub', models.CharField(default='001', max_length=90, verbose_name='后手模版id')),
                ('content', models.TextField(help_text='短信内容可有参，{{phone}}表示短信接收者的电话号码', max_length=2000, verbose_name='先手短信模版')),
                ('content_sub', models.TextField(default='未知', help_text='同上', max_length=1600, verbose_name='后手短信模版')),
                ('lang', models.SmallIntegerField(choices=[(1, '繁體'), (2, '英文')], default=1, null=True, verbose_name='语言')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sms.Category', verbose_name='服务分类')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sms.Service', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': '短信模版',
                'verbose_name_plural': '短信模版',
            },
        ),
    ]
