# Generated by Django 2.2.5 on 2020-07-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everytask',
            name='contact_key',
        ),
        migrations.AddField(
            model_name='everytask',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Contact', verbose_name='所属用户'),
        ),
    ]
