# Generated by Django 2.2.5 on 2020-06-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mark',
        ),
    ]
