# Generated by Django 2.2.5 on 2020-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sms', '0002_remove_smstemplate_is_para'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='flag_img',
        ),
        migrations.AlterField(
            model_name='category',
            name='flag',
            field=models.SmallIntegerField(choices=[(1, '疫苗'), (2, '手術'), (3, '美容'), (21, '產品'), (22, '服務'), (23, '檢查')], default=1, null=True, verbose_name='分类'),
        ),
    ]
